### ISSUE TITLE
desktop gsetting requirement

### ISSUE THREAD

**Issue by snyh** [martyr-deepin/deepin-system-settings#1]
1.  a way to find the default terminal application.   (used by launcher an no-gui application)
2.  a way to find the default icon theme.  (reference to the /usr/share/icons)
3.  a way to find someone file type can be opened by which applications. (reference to the /usr/share/applications/default.list)

**Comment by xiangzhai** [comment]
1. 默认终端
2. 图标主题
3. 文件类型

**Comment by xiangzhai** [comment]
1. org.gnome.desktop.default-applications.terminal
2. org.gnome.desktop.interface

**Comment by xiangzhai** [comment]
我们可以把这些也放到com.deepin.XXX中 :)
