### ISSUE TITLE
「功能缺失」WPA企业级加密支持

### ISSUE THREAD

**Issue by vizv** [martyr-deepin/deepin-system-settings#188]
请求增加对 WPA Enterprise 的加密支持。
学校用的 Protect EAP 加密的无线网络，因该项目功能缺失导致 LD 无法使用……

不是太会 python 所以帮不上忙，但感觉应该在
`modules/network/src/wlan_config.py`
这个文件下……

谢谢！

**Comment by manateelazycat** [comment]
Deepin 2014 会支持这些， 目前已经不用这个 Python 项目， 已经在 dss 中处理这些问题了。

2014-04-02 8:00 GMT+08:00 Wenxuan Zhao notifications@github.com:

**Comment by vizv** [comment]
Thanks，顺便问下 LD2014 有 Alpha 版嘛？想玩玩看~ 顺便可以找找 bug~
LD 蛮好看的，但是 2013.1 实在有好多功能没有……
