### ISSUE TITLE
pulseaudio dbus service start failed

### ISSUE THREAD

**Issue by yilang2007lw** [martyr-deepin/deepin-system-settings#2]
pulseaudio dbus service sometimes starts failed when pulseaudio daemon is runnig, even though restart it also doesn't work

**Comment by xiangzhai** [comment]
so how you wanna fix it? give some advice :)

**Comment by yilang2007lw** [comment]
kill the daemon first then restart it

**Comment by yilang2007lw** [comment]
use "pulseaudio --kill" and "pulseaudio --start", not "service pulseaudio restart"

**Comment by xiangzhai** [comment]
早点儿休息 :)

**Comment by yilang2007lw** [comment]
后续替换声音模块dbus扩展后端
