### ISSUE TITLE
./main.py display现实display模块，点击面包上的“系统设置”，就回不去navigation_page咯

### ISSUE THREAD

**Issue by xiangzhai** [martyr-deepin/deepin-system-settings#21]
点击ActionBar的下拉菜单的network模块，再点击“系统设置”，回到了navigation_page，但是display模块HOLD在了navigation_page后面。。。

**Comment by manateelazycat** [comment]
貌似这个Bug已经修复了？ 我没有测试出来

**Comment by xiangzhai** [comment]
还存在，不过有了历史backward && forward的解决思路，这个BUG也容易FIX咯 :)

**Comment by xiangzhai** [comment]
FIXED 使用goto消息类型，单实例抬起窗体 && 运行跳转到其他模块也支持咯
