### ISSUE TITLE
通过路径进行跳转、历史、搜索

### ISSUE THREAD

**Issue by xiangzhai** [martyr-deepin/deepin-system-settings#26]
*路径
NavigatePage即家界面home screen路径 /
声音 /sound
         /sound/advanced

*搜索
每个模块列出有哪些被搜索的关键词
在界面上的什么位置，如果继承ScrolledWindow，需要scrolled_to相应的位置
中文分词
界面高亮显示搜索关键词

**Comment by manateelazycat** [comment]
历史跳转已经做完了，
规律： 系统设置永远在第一个页面不参与位置动态调整， 其他子模块根据顺序保持相对位置， 但是整个历史循环列表中没有重复的（重复的没有意义），
最多只跳转到每个设置的第一个页面， 设置进一步的设置界面不参与历史记录（主要很多设置， 比如网络子设置是不可控的）

关于搜索和中文分词、以及界面高亮你们自己尝试做吧， 我可以提供技术建议。
团队的技术不要依赖我一个人， 团队就是需要不断挑战自我才能快速成长。

在 2012年12月26日下午11:28，xiangzhai notifications@github.com写道：

**Comment by xiangzhai** [comment]
感谢lazycat的dsc例子，dss现在也支持搜索了 https://github.com/linuxdeepin/deepin-system-settings/commit/de4819f04f68b601c458eaa0e55cc192c3dd93f4

剩下来的就是搜索页面的UI咯，哇哈哈 :)
