### ISSUE TITLE
在搜索结果页面再点击搜索后页面空白

### ISSUE THREAD

**Issue by wusuopu** [martyr-deepin/deepin-system-settings#29]
第一次搜索：
![ 20121229104646](https://f.cloud.github.com/assets/1478284/34949/057b4e8a-5162-11e2-9cdc-e10a6ea7a421.png)
再点搜索：
![ 20121229104653](https://f.cloud.github.com/assets/1478284/34950/08ddeb28-5162-11e2-8f00-edc1214f0611.png)

**Comment by xiangzhai** [comment]
FIXED
