### ISSUE TITLE
建议 尽量使用系统主题图标

### ISSUE THREAD

**Issue by snyh** [martyr-deepin/deepin-system-settings#35]
- preferences-color.png
- preferences-desktop-accessibility.png
- preferences-desktop-default-applications.png
- preferences-desktop-display.png
- preferences-desktop-font.png
- preferences-desktop-keyboard.png
- preferences-desktop-keyboard-shortcuts.png
- preferences-desktop-launch-feedback.png
- preferences-desktop-locale.png
- preferences-desktop-multimedia.png
- preferences-desktop-peripherals.png
- preferences-desktop-remote-desktop.png
- preferences-desktop-screensaver.png
- preferences-desktop-sound.png
- preferences-desktop-theme.png
- preferences-desktop-wallpaper.png
- preferences-sound.png
- preferences-system-bluetooth.png
- preferences-system-firewall.png
- preferences-system-network.png
- preferences-system-time.png
- preferences-system-windows.png

以上为xdg定义的标准icon name， 如果可以使用尽量直接使用这些名字。
没有的可以按照类似命名方式自行定义图标。

所有图标统一通过gtk_icon_theme的方式进行读取。
图标将存放在deepin-icon-theme里面.
theme = gtk.icon_theme_get_default()
icon_path = t.lookup_icon("preferences-system-windows", 48, gtk.ICON_LOOKUP_NO_SVG)

**Comment by xiangzhai** [comment]
bingo
