### ISSUE TITLE
主界面在英文 Locale 下仍为中文

### ISSUE THREAD

**Issue by lihongwu** [martyr-deepin/deepin-system-settings#42]
![deepin-system-settings](https://f.cloud.github.com/assets/2755805/70546/54d58b9e-5fae-11e2-8181-0e566765e9c1.png)

现提供相应英文翻译，烦请开发人员进行相应修正（修正时，请注意大小写及拼写均与给出翻译相符）。

另外，建议将中文的“驱动”一项改为“附加驱动”，因该项不能完全反映Linux内核对于本机的全部驱动模块。

英文翻译已附于下方：

系统设置 - System Settings

显示 - Displays

声音 - Sound

个性化 - Individualization

日期时间 - Time & Date

电源 - Power

键盘 - Keyboard

鼠标 - Mouse

触摸版 - Touchpad

打印机 - Printers

网络 - Network

蓝牙 - Bluetooth

驱动 - Additional Drivers

账户设置 - User Accounts

应用程序关联 - Default Applications

系统信息 - System Information

**Comment by tuhaihe** [comment]
@xiangzhai 

请仔细参照上面给出的英文翻译校对当前的英文，部分还没有修改过来。

如，日期时间，英文应为 “Time & Date”，但还是显示 Date Time，没有修改过来。

@lihongwu @tuhaihe
