### ISSUE TITLE
显示设置的恢复默认功能不全！

### ISSUE THREAD

**Issue by gaochao001** [martyr-deepin/deepin-system-settings#50]
显示设置中，亮度、自动调节屏幕亮度、自动锁定用户屏幕、恢复不了默认！

**Comment by xiangzhai** [comment]
1. 每个模块都会依赖GSettings，然后调用g_settings_reset http://developer.gnome.org/gio/2.32/GSettings.html#g-settings-reset 来进行“恢复默认”值；
2. 但是有些数值在GSettings中是没有的，甚至是使用XML来存储的 ~/.config/monitors.xml 该XML文件就是Gnome Settings Daemon生成的，用于记录多configure、多output的数值，那么这种类型的数值就无法恢复默认了；
