### ISSUE TITLE
[Bug]“显示”：屏幕分辨率无法与命令行同步

### ISSUE THREAD

**Issue by tuhaihe** [martyr-deepin/deepin-system-settings#52]
@xiangzhai 
当在命令行设置一个屏幕分辨率后，“系统设置-显示”中的分辨率显示与命令行设置的不一样。
@gaochao001 @lihongwu

**Comment by xiangzhai** [comment]
1. xrandr http://www.x.org/wiki/Projects/XRandR 是独立与GSettings、Gnome Settings Dameon的应用程序，它对分辨率、旋转等参数的修改，没有和GSD进行同步；
2. 我们的DSS依赖GS、GSD，主要在GS中进行了数值上的修改，DSS中都可以同步；
