### ISSUE TITLE
[Bug]“显示”：无法自动调节屏幕亮度

### ISSUE THREAD

**Issue by tuhaihe** [martyr-deepin/deepin-system-settings#53]
@xiangzhai 
## 1 锁定屏幕

当关闭“自动锁定用户屏幕”时，“锁定屏幕”时间应设为“从不”或直接无法让用户选择锁定屏幕时间；

@gaochao001 @lihongwu

**Comment by xiangzhai** [comment]
嗯呐，我来FIX

**Comment by xiangzhai** [comment]
现在改为 "直接无法让用户选择锁定屏幕时间" CHECK IT OUT :)
