### ISSUE TITLE
[Bug]“日期时间”：农历节日提示无法看清（更新）

### ISSUE THREAD

**Issue by tuhaihe** [martyr-deepin/deepin-system-settings#56]
@xiangzhai 
## 1，“当前日期”显示不完整，后面出现省略号

其他地方也有显示不完整：

*\* 同样，关闭“自动设置时间”，手动设置后面的时间显示也不完整，框太小。（英文下也是）

*\*  英文状态下：部分月底日期显示不全，太靠下了；

*\* 英文状态下：24 Hour Display---> 24 Hour Time (参考 Ubuntu 英文显示)
## 2，农历节日提示背景白色，看不清

截图：http://i.imgur.com/ak8yD74.png

@gaochao001 @lihongwu

**Comment by xiangzhai** [comment]
农历节日提示背景白色，这个需要做系统主题的哥们儿FIX :)
