### ISSUE TITLE
[Bug]“网络”：新建名称错误

### ISSUE THREAD

**Issue by tuhaihe** [martyr-deepin/deepin-system-settings#58]
## 2 VPN 设置，下划线不一致

“VPN”、“设置”，底部的下划线不一样。

@yilang2007lw @cursorzz

**Comment by yilang2007lw** [comment]
网络连接没保存就占用一个编号不太合理，这需要把号码静态写入系统但中间很多又不存在。gnome的处理方式也是我们现在这样
