### ISSUE TITLE
wireless device unavailabe when move working place

### ISSUE THREAD

**Issue by yilang2007lw** [martyr-deepin/deepin-system-settings#7]
lspci and d-feet show the wireless device normally, but device state is not active.
when it happens, no dhcp config or ip config dbus interface.
The state reason is auto ip failed

**Comment by yilang2007lw** [comment]
It may occures when the wireless connection works well, must restart computer to fix it. 
The first state is device unknown, reason is a dependency of the connection failed. 
when restart network-manager or logout, the state reason comes to be auto ip failed

**Comment by xiangzhai** [comment]
Longwei add oil, add oil :)

**Comment by yilang2007lw** [comment]
可能的解决方法：
1.sudo gedit /etc/modprobe.d/blacklist.conf, 加入blacklist acer-wmi, 通过bios禁用再启用无线网卡

2.#sudo gedit /var/lib/NetworkManager/NetworkManager.state
[main]
NetworkingEnabled=true
WirelessEnabled=true
WWANEnabled=true  
把true修改成false

3.rfkill unblock all

4.解压无线网卡驱动至/lib/firmware

**Comment by yilang2007lw** [comment]
出现此问题时无线网卡不可用，执行以下命令可解决：
1.sudo  iwconfig wlan0 power on
2.sudo service network-manager restart
在不需要关机的情况下把无线网卡刷一遍，再找找相关的编程API
