### ISSUE TITLE
[Bug]“日期时间”：模块崩溃

### ISSUE THREAD

**Issue by tuhaihe** [martyr-deepin/deepin-system-settings#73]
@xiangzhai 
- 1，点击“恢复默认”出现崩溃 
- 2，节日提示蓝色过重，看不清楚
- 3，手动设置时间不工作
- 4, "恢复默认"无法将修改的日期与时间、时区调整到原来状态。
  同时，这个“恢复默认”偶尔不出现，返回切换日期时间模块才能出现。

---

@gaochao001 @lihongwu @tuhaihe

**Comment by yilang2007lw** [comment]
@xiangzhai 暂时把NTP同步功能从界面上干掉

**Comment by xiangzhai** [comment]
好吧。。。
