### ISSUE TITLE
[Bug]“日期时间”：农历tip显示位置调整

### ISSUE THREAD

**Issue by tuhaihe** [martyr-deepin/deepin-system-settings#74]
@xiangzhai 

在“系统设置-日期时间”模块，当鼠标移动到除当前日期外的其他地方（包括其他日期）时，仍旧显示当前日期信息。
如下图，鼠标指向了 27 日，却仍显示 25 日信息，建议修改。

![2013-01-25-102139_1440x900_scrot](https://f.cloud.github.com/assets/1284465/96202/c86eb60e-6696-11e2-90eb-ce29157de98f.png)

---

@gaochao001 @lihongwu

**Comment by xiangzhai** [comment]
点击后才响应，不点击仅仅移动鼠标，显示当前日期信息
