### ISSUE TITLE
声音前端界面出现奇怪的现象

### ISSUE THREAD

**Issue by xiangzhai** [martyr-deepin/deepin-system-settings#79]
![20130218092134](https://f.cloud.github.com/assets/851100/165713/fa04b39a-7969-11e2-9244-d1cd2f19aee7.png)

**Comment by manateelazycat** [comment]
这个是因为重绘的区域不够大, 导致Plug控件缩放时残影, 正确的修复方法是Plug下的容器重新绘制一次.
