### ISSUE TITLE
{细节}系统设置的日期时间设置中手动设置

### ISSUE THREAD

**Issue by gaochao001** [martyr-deepin/deepin-system-settings#80]
+++调节自动设置时间时会出现手动设置时间的条框不完整
![QQ 20130313102514](https://f.cloud.github.com/assets/2724795/252082/cc33108c-8b85-11e2-92d3-37cc816321ac.png)
或者是出现不能隐藏的线条
![QQ 20130313102823](https://f.cloud.github.com/assets/2724795/252084/f4ee3d62-8b85-11e2-9050-53ab71182641.png)

**Comment by xiangzhai** [comment]
好，我来看看

**Comment by xiangzhai** [comment]
FIXED :)

https://github.com/linuxdeepin/deepin-system-settings/commit/99a12f624f5c7d0d73b5490ab030d971d0d9bb63
