### ISSUE TITLE
更改屏幕分辨率后出现多处混乱现象

### ISSUE THREAD

**Issue by gaochao001** [martyr-deepin/deepin-system-settings#81]
++++系统设置/显示设置
![ 20130321094617](https://f.cloud.github.com/assets/2724795/283996/e8febfc8-91c9-11e2-9f4e-894e35a18453.png)
++++屏幕出现混乱、僵死，dock出现残影
![ 20130321094903](https://f.cloud.github.com/assets/2724795/284005/20d6691e-91ca-11e2-96a7-29c0eddec4f8.png)
++++desktop图标出现混乱排列
![ 20130321094940](https://f.cloud.github.com/assets/2724795/284010/60e000e2-91ca-11e2-87c5-e0a7e3e4a753.png)

**Comment by xiangzhai** [comment]
dss的显示BUG好FIX
