### ISSUE TITLE
系统设置的桌面设置

### ISSUE THREAD

**Issue by gaochao001** [martyr-deepin/deepin-system-settings#82]
++++取消桌面图标的四个图标的勾选，然后恢复默认桌面的图标恢复不完全，设置中的图标没有恢复勾选！返回再次进入恢复默认按钮消失！其他设置恢复默认无效！
![ 20130321095941](https://f.cloud.github.com/assets/2724795/284033/b81bcf7a-91cb-11e2-942f-47deee88ec86.png)

**Comment by xiangzhai** [comment]
FIXED :)
